name: bubble_chart
description: A beautiful and interactive bubble chart widget for Flutter with physics-based animations. Perfect for visualizing market data, statistics, and dynamic datasets.
version: 1.0.0
homepage: https://github.com/zengchao928/bubble_chart
repository: https://github.com/zengchao928/bubble_chart
issue_tracker: https://github.com/zengchao928/bubble_chart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
